### ISSUE TITLE
Model From Stream

### ISSUE THREAD

**Issue by hakanseysane** [bzinchenko/bpmnview#8] opened 2018-07-05 15:07 UTC
Hi, we have a web service and we save all files (bpmn) as binary data on the database.
i trying to get model from base64 but there is no feature like this in BPMN.Sharp.

Can you add a new feature about getting model from binary data, not only filename.

Thanks

**Comment by bzinchenko** [comment] 2018-07-09 09:42
Hello @hakanseysane. Your question is duplicate of another issue, which is resolved long ago: #2. Please use the function `Model Parse(string xml)` to load XML directly. You can store XML as base64 or as a string field in your database. I see no merit in base64 encoding. But there is no harm either. Do not forget to decode base64 prior to function call.

**Closed by bzinchenko** 2018-07-09 09:42 UTC
